### ISSUE TITLE
Loss of Instagram authorization completely breaks PicPuller requiring an uninstall/install.

### ISSUE THREAD

**Issue by janson** [jmx2inc/picpuller-for-craft3#6]
In the course of a site launch, PicPuller lost authorization to our Instagram User. This completely broke the template, and threw server 500 errors when trying to get to the PicPuller control panel screens to adjust. 

This same json_decode() error was thrown by the CP @ /admin/pic-puller and anywhere the templates tried to display the feed.

![screen shot 2018-08-20 at 11 38 54 am](https://user-images.githubusercontent.com/793/44351566-28a51500-a470-11e8-9f43-1936ea29db96.png)

**Comment by johnfmorton** [comment]
Taking a look. Back with more info soon.

**Comment by johnfmorton** [comment]
I've just pushed 3.0.12 which should address this. Please let me know if you run into other issues. Thanks.

**Comment by janson** [comment]
I'm still getting a (related) exception when we hit Instagram rate limits:

![screen shot 2018-08-20 at 5 40 02 pm](https://user-images.githubusercontent.com/793/44368240-35416180-a4a0-11e8-839e-96dc23ffbf0b.png)

**Comment by janson** [comment]
_Edit_ I should note that the original issues in the ticket were down to rate limits rather than un-authorization. (Thus, Instagram's API is returning a OAuthRateLimitException / 429.)

**Comment by johnfmorton** [comment]
I fixed one issue and exposed an old one I thought I squashed. Sorry about that. Working on a fix.
